# Generated by Django 5.0.6 on 2024-07-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudApp', '0002_studentregistration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='Gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
