# Generated by Django 5.0.7 on 2024-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, max_length=50, null=True)),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='Category_Pictures')),
            ],
        ),
        migrations.CreateModel(
            name='ProDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=50, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('BrandName', models.CharField(blank=True, max_length=50, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='Product_Pictures')),
                ('ProductImage1', models.ImageField(blank=True, null=True, upload_to='Product_Pictures')),
                ('ProductImage2', models.ImageField(blank=True, null=True, upload_to='Product_Pictures')),
            ],
        ),
    ]
