# Generated by Django 5.0.7 on 2024-08-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodb',
            name='ProductImage3',
            field=models.ImageField(blank=True, null=True, upload_to='Product_Pictures'),
        ),
        migrations.AddField(
            model_name='prodb',
            name='ProductImage4',
            field=models.ImageField(blank=True, null=True, upload_to='Product_Pictures'),
        ),
    ]
