# Generated by Django 5.0.7 on 2024-08-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0003_alter_prodb_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodb',
            name='BrandName',
        ),
    ]
