# Generated by Django 5.0.7 on 2024-09-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0004_remove_prodb_brandname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodb',
            name='Price',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
