# Generated by Django 5.0.7 on 2024-09-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0005_alter_prodb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
