# Generated by Django 5.0.7 on 2024-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0006_alter_prodb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasslistDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('ClassImage', models.ImageField(blank=True, null=True, upload_to='Class_Pictures')),
            ],
        ),
    ]
