# Generated by Django 5.0.6 on 2024-07-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Company', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile_Number', models.IntegerField(blank=True, null=True)),
                ('Salary', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
