# Generated by Django 5.0.7 on 2024-09-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRegistrationDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('StudyingClass', models.CharField(blank=True, choices=[('Online', 'OnlineClass'), ('Offline', 'OfflineClass')], max_length=100, null=True)),
                ('OnlineClass', models.CharField(blank=True, max_length=100, null=True)),
                ('OfflineClass', models.CharField(blank=True, max_length=100, null=True)),
                ('Requirements', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
