# Generated by Django 5.0.7 on 2024-09-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_classregistrationdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classregistrationdb',
            name='OfflineClass',
        ),
        migrations.RemoveField(
            model_name='classregistrationdb',
            name='OnlineClass',
        ),
    ]
