# Generated by Django 5.0.7 on 2024-09-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_remove_classregistrationdb_offlineclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
