# Generated by Django 5.0.7 on 2024-09-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_remove_teamdb_qualification_teamdb_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdb',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
