# Generated by Django 5.0.7 on 2024-09-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_testimonialdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonialdb',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonialdb',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
