# Generated by Django 5.0.7 on 2024-09-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
