# Generated by Django 5.0.7 on 2024-09-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_discountcode_valid_from_discountcode_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='cartdb',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
