# Generated by Django 5.0.7 on 2024-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_rename_firstname_checkoutdb_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutDb',
            new_name='OrderDb',
        ),
    ]
