# Generated by Django 5.0.7 on 2024-09-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_rename_checkoutdb_orderdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Total_price', models.IntegerField(blank=True, null=True)),
                ('Stock', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
