# Generated by Django 5.0.7 on 2024-09-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_wishlistdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistdb',
            old_name='Stock',
            new_name='Username',
        ),
    ]
