# Generated by Django 5.0.7 on 2024-09-30 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0006_alter_prodb_price'),
        ('WebApp', '0020_remove_wishlistdb_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistdb',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='wishlistdb',
            name='Product_name',
        ),
        migrations.RemoveField(
            model_name='wishlistdb',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='wishlistdb',
            name='Username',
        ),
        migrations.AddField(
            model_name='wishlistdb',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wishlistdb',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CafeApp.prodb'),
        ),
        migrations.AddField(
            model_name='wishlistdb',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
