# Generated by Django 5.0.7 on 2024-09-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0021_remove_wishlistdb_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistdb',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='wishlistdb',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistdb',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlistdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistdb',
            name='Product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wishlistdb',
            name='Stock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wishlistdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
