# Generated by Django 5.0.7 on 2024-09-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0022_remove_wishlistdb_added_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistdb',
            old_name='Price',
            new_name='Total_price',
        ),
    ]
