# Generated by Django 5.0.7 on 2024-09-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0023_rename_price_wishlistdb_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistdb',
            old_name='Total_price',
            new_name='Pice',
        ),
    ]
