# Generated by Django 5.0.7 on 2024-09-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0024_rename_total_price_wishlistdb_pice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistdb',
            old_name='Pice',
            new_name='Price',
        ),
    ]
