# Generated by Django 5.0.7 on 2024-09-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0025_rename_pice_wishlistdb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistdb',
            name='Stock',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=100),
        ),
    ]
