# Generated by Django 5.0.7 on 2024-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0027_rename_product_name_wishlistdb_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistdb',
            name='Stock',
            field=models.CharField(blank=True, choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], max_length=100, null=True),
        ),
    ]
