# Generated by Django 5.0.7 on 2024-10-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0028_alter_wishlistdb_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='Total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
