# Generated by Django 5.0.7 on 2024-10-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0030_classlistdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.RenameField(
            model_name='classlistdb',
            old_name='additional_info',
            new_name='Additional_info',
        ),
        migrations.RenameField(
            model_name='classlistdb',
            old_name='class_name',
            new_name='ClassName',
        ),
        migrations.RenameField(
            model_name='classlistdb',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='classlistdb',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='classlistdb',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='classlistdb',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='classlistdb',
            old_name='time',
            new_name='Time',
        ),
    ]
