# Generated by Django 5.0.7 on 2024-10-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0031_delete_discountcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlistdb',
            name='Additional_info',
        ),
    ]
