# Generated by Django 5.0.7 on 2024-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0033_contactaddressdb_delete_classlistdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddressdb',
            name='Place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
