# Generated by Django 5.0.7 on 2024-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0034_contactaddressdb_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddressdb',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
