# Generated by Django 5.0.7 on 2024-10-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0035_contactaddressdb_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactAddressDb',
        ),
        migrations.AddField(
            model_name='contactdb',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactdb',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactdb',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactdb',
            name='Place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
