# Generated by Django 5.0.7 on 2024-10-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0037_alter_contactdb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactdb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='contactdb',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='contactdb',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='contactdb',
            name='Place',
        ),
    ]
