# Generated by Django 5.0.7 on 2024-10-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0039_contactinfodb_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfodb',
            name='Phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
