# Generated by Django 5.0.7 on 2024-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0040_alter_contactinfodb_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfodb',
            name='Description1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfodb',
            name='Description2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfodb',
            name='Description3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
