# Generated by Django 5.0.7 on 2024-10-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0041_contactinfodb_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description1', models.CharField(blank=True, max_length=100, null=True)),
                ('Description2', models.CharField(blank=True, max_length=100, null=True)),
                ('Description3', models.CharField(blank=True, max_length=100, null=True)),
                ('Description4', models.CharField(blank=True, max_length=100, null=True)),
                ('Description5', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
