# Generated by Django 5.0.7 on 2024-10-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0043_orderdb_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, max_length=100, null=True)),
                ('Description1', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
