# Generated by Django 5.0.7 on 2024-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0044_aboutdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdb',
            name='Description',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='aboutdb',
            name='Description1',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
