# Generated by Django 5.0.7 on 2024-08-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_orderdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdb',
            name='Price',
        ),
    ]
