# Generated by Django 5.0.6 on 2024-07-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(blank=True, max_length=50, null=True)),
                ('AuthorName', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('PublishedDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
