# Generated by Django 5.0.7 on 2024-07-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(blank=True, max_length=50, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('OwnerName', models.CharField(blank=True, max_length=50, null=True)),
                ('ShopType', models.CharField(blank=True, max_length=50, null=True)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='Profile_Pictures')),
            ],
        ),
    ]
